[package]
name = "turborepo"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.61.0"
build-target = "0.4.0"

[dev-dependencies]
assert_cmd = "2.0.6"
itertools = "0.10.5"

[dependencies]
anyhow = { version = "1.0.65", features = ["backtrace"] }
# Because we use ignore_errors in clap, we have to stick to v3 instead of v4
# due to issues such as: https://github.com/clap-rs/clap/issues/4391
clap = { version = "3.2.23", features = ["derive"] }
globset = "0.4.9"
predicates = "2.1.1"
# semver does note that it is designed to parse Cargo's interpretation of semver.
# Therefore we cannot use it to parse semver strings in general. However, it is
# good enough to parse semver strings that we control, i.e. turbo's own version
semver = "1.0.14"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
serde_yaml = "0.8.26"
walkdir = "2"
yarn-lock-parser = "0.4.0"
