[package]
name = "turbo"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[features]
# By default, we enable native-tls for reqwest via downstream transitive features.
# This is for the convenience of running daily dev workflows, i.e running
# `cargo xxx` without explicitly specifying features, not that we want to
# promote this as default backend.
default = ["rustls-tls"]
native-tls = ["turborepo-lib/native-tls"]
rustls-tls = ["turborepo-lib/rustls-tls"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
build-target = "0.4.0"

[dev-dependencies]
assert_cmd = { workspace = true }
itertools = { workspace = true }
pretty_assertions = { workspace = true }

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
command-group = { version = "2.0.1", features = ["with-tokio"] }
dunce = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tiny-gradient = { workspace = true }
tokio-util = { version = "0.7.7", features = ["io"] }
tracing = { workspace = true }
turborepo-lib = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.3.9"
