[package]
name = "turbo"
version = "2.0.2-canary.1"
edition = "2021"
license = "MIT"

[package.metadata.dist]
dist = true

[features]
# By default, we enable rustls-tls for reqwest via downstream transitive features.
# This is for the convenience of running daily dev workflows, i.e running
# `cargo xxx` without explicitly specifying features, not that we want to
# promote this as default backend.
default = ["rustls-tls", "turborepo-lib/daemon-package-discovery"]
native-tls = ["turborepo-lib/native-tls"]
rustls-tls = ["turborepo-lib/rustls-tls"]
pprof = ["turborepo-lib/pprof"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
build-target = "0.4.0"

[dev-dependencies]
assert_cmd = { workspace = true }
itertools = { workspace = true }
pretty_assertions = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
human-panic = "1.2.1"
miette.workspace = true
turborepo-lib = { workspace = true, default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.3.9"
