[package]
name = "turborepo-engine"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

[lints]
workspace = true

[dependencies]
convert_case = "0.6.0"
futures = { workspace = true }
itertools = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
petgraph = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
turbopath = { workspace = true }
turborepo-config = { path = "../turborepo-config" }
turborepo-errors = { workspace = true }
turborepo-graph-utils = { path = "../turborepo-graph-utils" }
turborepo-repository = { path = "../turborepo-repository" }
turborepo-task-id = { path = "../turborepo-task-id" }
turborepo-turbo-json = { path = "../turborepo-turbo-json" }
turborepo-types = { workspace = true }
which = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }
turborepo-lockfiles = { path = "../turborepo-lockfiles" }
turborepo-turbo-json = { path = "../turborepo-turbo-json" }
