# .kodiak.toml
version = 1

[merge]
automerge_label = "pr: automerge"
require_automerge_label = true
blocking_labels = ["pr: fixship", "pr: on hold", "pr: work in progress"]
method = "squash"
delete_branch_on_merge = true
optimistic_updates = true
prioritize_ready_to_merge = true
notify_on_conflict = false

[update]
# https://kodiakhq.com/docs/config-reference#updatealways
# always "update" (i.e. merge main branch into PR), if it has the automerge_label.
# Without this, only branches that are passing CI will get updated.
# The benefit of this config is that PRs that we want to automerge, but
# have failed because the test suite is flaky will get stuck, unless someone
# presses the Update Branch button manually, or re-triggers the Github workflow
# for tests again. This causes delays in getting easy PRs in.
always = true

# https://kodiakhq.com/docs/config-reference#updateautoupdate_label
# PRs will get updates from the base branch (i.e. usually `main`)
# when this label is applied. This is different from "update=always"
# config, which only applies to PRs that have been tagged with for auto_merging_
# (i.e. PRs with the "pr: automerge" label, which is configured above).
# This label allows PR authors to keep their PR branch up-to-date without
# opting into Kodiak's automerge feature. This is useful if you want to use
# Github's AutoMerge feature instead.
autoupdate_label = "pr: autoupdate"

[merge.message]
title = "pull_request_title"
include_coauthors= true
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
