[package]
name = "turborepo-vt100"
version = "0.15.2"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = { workspace = true }

description = "Library for parsing terminal data"
homepage = "https://github.com/doy/vt100-rust"
repository = "https://github.com/doy/vt100-rust"
readme = "README.md"
keywords = ["terminal", "vt100"]
categories = ["command-line-interface", "encoding"]
license = "MIT"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[features]
default = ["tui-term"]
tui-term = ["dep:tui-term", "dep:ratatui"]

[dependencies]
itoa = "1.0.9"
log = "0.4.19"
ratatui = { workspace = true, optional = true }
tui-term = { workspace = true, optional = true }
unicode-width = "0.1.10"
vte = "0.11.1"

[dev-dependencies]
quickcheck = "1.0"
rand = "0.8"
serde = { version = "1.0.182", features = ["derive"] }
serde_json = "1.0.104"
terminal_size = "0.2.6"
vte = "0.11.1"
