[package]
name = "turborepo-napi"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
napi = { version = "2.14.0", features = ["tokio_rt"] }
napi-derive = "2.14.0"
thiserror = { workspace = true }
tokio = { workspace = true }
turbopath = { workspace = true }
turborepo-repository = { workspace = true }

[build-dependencies]
napi-build = "2.0.1"
