[package]
name = "turborepo-scm"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
bstr = "1.4.0"
git2 = { workspace = true, default-features = false, optional = true }
globwalk = { path = "../turborepo-globwalk" }
hex = { workspace = true }
ignore = "0.4.20"
nom = "7.1.3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = "0.10.5"
thiserror = { workspace = true }
tracing = { workspace = true }
turbopath = { workspace = true }
turborepo-ci = { workspace = true }
turborepo-telemetry = { path = "../turborepo-telemetry" }
wax = { workspace = true }
which = { workspace = true }

[dev-dependencies]
git2 = { workspace = true, default-features = false }
tempfile = { workspace = true }
test-case = "3.1.0"

[features]
git2 = ["dep:git2"]
