[package]
name = "turborepo-scm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dunce = "1.0.3"
git2 = "0.16.1"
tempfile = "3.3.0"
thiserror = "1.0.38"
