[package]
name = "turborepo-scm"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "1.4.0"
git2 = { version = "0.16.1", default-features = false }
globwalk = { path = "../turborepo-globwalk" }
hex = { workspace = true }
ignore = "0.4.20"
itertools.workspace = true
nom = "7.1.3"
qp-trie = "0.8.2"
sha1 = "0.10.5"
thiserror = { workspace = true }
tracing = { workspace = true }
turbopath = { workspace = true }
wax = { workspace = true }
which = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
test-case = "3.1.0"
