[package]
name = "turborepo-dirs"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs-next = "2.0.0"
thiserror.workspace = true
turbopath = { workspace = true }

[lints]
workspace = true
