[package]
name = "turborepo-fs"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
fs-err = "2.9.0"
thiserror = "1.0.38"
turbopath = { workspace = true }
walkdir = "2.3.3"

[dev-dependencies]
tempfile = { workspace = true }
