[package]
name = "turborepo-fs"
version = "0.1.0"
license = "MIT"
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
fs-err = "2.9.0"
ignore = "0.4.22"
thiserror = "1.0.38"
turbopath = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
test-case = { workspace = true }
