[package]
name = "turborepo-telemetry"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dev-dependencies]
serde_json = { workspace = true }
test-case = { workspace = true }
turborepo-vercel-api-mock = { workspace = true }

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
config = "0.13.4"
dirs-next = "2.0.0"
futures = { workspace = true }
hex = "0.4.3"
once_cell = "1.18.0"
reqwest = { workspace = true, features = ["json"] }
rustc_version_runtime = "0.3.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = "0.10.8"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full", "time"] }
tracing = { workspace = true }
turborepo-api-client = { workspace = true }
turborepo-dirs = { path = "../turborepo-dirs" }
turborepo-ui = { workspace = true }
turborepo-vercel-api = { workspace = true }
url = { workspace = true }
uuid = { version = "1.5.0", features = ["v4"] }
