[package]
name = "turborepo-unescape"
version = "0.1.0"
edition = { workspace = true }
license = "MPL-2.0"

[dependencies]
biome_deserialize = { workspace = true }
schemars = { workspace = true }
serde.workspace = true
serde_json.workspace = true
ts-rs = { workspace = true }

[lints]
workspace = true
