[package]
name = "turborepo-vercel-api-mock"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
futures-util = "0.3.28"
port_scanner = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
turborepo-vercel-api = { workspace = true }
