[package]
name = "turborepo-graph-utils"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
fixedbitset = "0.4.2"
futures = "0.3.26"
itertools = { workspace = true }
log = "0.4.20"
petgraph = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full", "time"] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
insta = { workspace = true }
