[package]
name = "turborepo-lockfiles"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5.6"
pest_derive = "2.5.6"
regex = "1"
semver = "1.0.17"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.86"
serde_yaml = "0.9"
thiserror = "1.0.38"

[dev-dependencies]
pretty_assertions = "1.3"
