[package]
name = "turborepo-gitignore"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

[dependencies]
turbopath = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
