[package]
name = "turborepo-errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { workspace = true }
miette = { workspace = true }
serde = { workspace = true, features = ["derive"] }
