[package]
name = "turborepo-errors"
version = "0.1.0"
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
biome_deserialize = { workspace = true }
biome_diagnostics = { workspace = true }
biome_json_parser = { workspace = true }
miette = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true
