[package]
name = "turborepo-env"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
hex = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
turborepo-ci = { workspace = true }
turborepo-ui = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
