[package]
name = "turborepo-task-id"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

[lints]
workspace = true

[dependencies]
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
ts-rs = { workspace = true }
turborepo-repository = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
