[package]
name = "turborepo-vercel-api"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
insta = { version = "1.34.0", features = ["json"] }
serde_json = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true }
url = { workspace = true }
