[package]
name = "turborepo-otel"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

[dependencies]
opentelemetry = { version = "0.31", features = ["metrics"] }
opentelemetry-otlp = { version = "0.31", features = [
  "grpc-tonic",
  "http-proto",
  "metrics",
] }
opentelemetry-semantic-conventions = "0.31"
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio", "metrics"] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tonic = "0.14"
tracing = { workspace = true }

[features]
default = []
serde = ["dep:serde", "dep:serde_json"]
