[package]
name = "update-notifier"
version = "0.1.0"
edition = "2021"
description = "Output update notification to the console when new version on npm package is available"
license = "MPL-2.0"
publish = false


[dependencies]
colored            = "2.0"
env_logger         = "0.10"
log                = "0.4"
reqwest            = { version = "0.11", features = ["json"] }
semver             = "1.0"
serde              = { version = "1.0.126", features = ["derive"] }
serde_json         = { version = "1.0.87" }
strip-ansi-escapes = "0.1.1"
terminal_size      = "0.2"
thiserror          = "1.0"
tiny-gradient      = "0.1"
tokio              = { version = "1", features = ["full"] }
