[package]
name = "turborepo-filewatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
dashmap = { workspace = true }
futures = { version = "0.3.26" }
notify = "6.0.1"
notify-debouncer-full = { version = "0.2.0", default-features = false }
thiserror = "1.0.38"
tokio = { workspace = true, features = ["full", "time"] }
turbopath = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
