[package]
name = "turborepo-filewatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
notify = "6.0.1"
notify-debouncer-full = { version = "0.2.0", default-features = false }
thiserror = "1.0.38"
tokio = { workspace = true, features = ["full", "time"] }
turbopath = { workspace = true }
walkdir = "2.3.3"

[target."cfg(target_os=\"macos\")".dependencies.fsevent-sys]
optional = true
version = "4"

[dependencies.bitflags]
version = "1.0.4"

[dependencies.libc]
version = "0.2.4"

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = ["macos_fsevent"]
macos_fsevent = ["fsevent-sys"]
