[package]
name = "turborepo-ui"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
anyhow = { workspace = true }
indoc = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true

[dependencies]
atty = { workspace = true }
base64 = "0.22"
chrono = { workspace = true }
console = { workspace = true }
crossterm = "0.27.0"
dialoguer = { workspace = true }
indicatif = { workspace = true }
lazy_static = { workspace = true }
nix = { version = "0.26.2", features = ["signal"] }
ratatui = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tui-term = { workspace = true }
turbopath = { workspace = true }
turborepo-ci = { workspace = true }
turborepo-vt100 = { workspace = true }
which = { workspace = true }
winapi = "0.3.9"

[target."cfg(windows)".dependencies]
clipboard-win = "5.3.1"
