[package]
name = "turborepo-ui"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
anyhow = { workspace = true }
indoc = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true

[dependencies]
async-graphql = { workspace = true }
atty = { workspace = true }
axum = { workspace = true, features = ["ws"] }
base64 = "0.22"
chrono = { workspace = true }
console = { workspace = true }
crossterm = { version = "0.27.0", features = ["event-stream"] }
dialoguer = { workspace = true }
futures = { workspace = true }
indicatif = { workspace = true }
lazy_static = { workspace = true }
nix = { version = "0.26.2", features = ["signal"] }
ratatui = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tui-term = { workspace = true }
turbopath = { workspace = true }
turborepo-ci = { workspace = true }
turborepo-vt100 = { workspace = true }
which = { workspace = true }

[target."cfg(windows)".dependencies]
clipboard-win = "5.3.1"
windows-sys = { version = "0.59", features = ["Win32_System_Console"] }
