name: Bench against @vercel/nft

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened, edited]
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_RELEASE_LTO: true
  RUST_BACKTRACE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  bench_vs_node_nft:
    # for edited events it should only run on base changes
    if: ${{ github.event.action != 'edited' || github.event.changes.base }}
    runs-on: ubuntu-latest
    name: Bench against Node.js nft

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
        with:
          key: bench_nft

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16

      - name: install Node.js dependencies
        run: yarn install

      - name: Install nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
        shell: bash

      - name: Run benchmark
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run -j 1 --no-fail-fast -r -p turbopack --features bench_against_node_nft bench_against_node_nft

      - name: Show benchmark result
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: nft-bench-result
