name: Build Rust cache

on:
  push:
    branches: [main]
  # TODO: remove this after testing
  pull_request:
    branches: [main]

jobs:
  build_cache_tools:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu
            # myb use 16 core, idk
            runner: ubuntu-latest-16-core-oss
          - name: macos
            runner: macos-latest
          - name: windows
            runner: windows-latest

    runs-on: ${{ matrix.os.runner }}
    name: Building Rust cache tools for ${{ matrix.os.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          components: clippy
          shared-cache-key: dependencies
          save-cache: true

      - name: Install cargo-chef
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-chef

  build_cache:
    name: Building Rust cache for ${{ matrix.os.name }}
    needs: [build_cache_tools]

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu
            # myb use 8 core, idk
            runner: ubuntu-latest-16-core-oss
          - name: macos
            runner: macos-latest
          - name: windows
            runner: windows-latest

    runs-on: ${{ matrix.os.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          components: clippy
          shared-cache-key: dependencies
          save-cache: true

      # TODO: remove this after testing
      - name: Test Cache Size
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: dependencies

      - name: Install cargo-chef
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-chef

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Compile dependencies
        # We exclude turbo as it requires linking Go and all logic resides in turborepo-lib
        run: |
          cargo chef prepare
          cargo chef cook --workspace --all-targets
          cargo chef cook --workspace --all-targets --release

      - name: Compile check / clippy dependencies
        if: matrix.os.name == 'ubuntu'
        run: |
          cargo chef cook --workspace --all-targets --check
          cargo chef cook --workspace --all-targets --check --release
          cargo chef cook --workspace --all-targets --clippy

      - name: Compile nextest dependencies
        run: |
          cargo nextest run --no-run --release --workspace --exclude turbo

  cleanup:
    name: Cleanup
    needs: [build_cache]
    if: always()
    uses: ./.github/workflows/pr-clean-caches.yml
    secrets: inherit
