name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: build and test
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
        id: go

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - name: Build & Unit Test
        run: yarn turbo run test --scope=cli

      - name: Lint
        run: yarn turbo run lint --scope=cli

      - name: E2E Tests
        run: |
          npm install -g pnpm
          cd cli && make e2e

      - name: Benchmark and Smoke Tests
        run: cd cli && make bench/turbo

      - name: Benchmark E2E
        run: cd cli && make bench/e2e

      - name: Store Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "${{ runner.os }} Benchmark"
          # What benchmark tool the output is formatted as
          tool: "customSmallerIsBetter"
          output-file-path: ./cli/scripts/benchmarks.json
          benchmark-data-dir-path: benchmarks/e2e/${{ runner.os }}
          auto-push: ${{ github.event_name == 'push' }}
          comment-on-alert: true
          comment-always: true
          # GitHub API token to make a commit on push, and a comment always
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    name: build and test
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
        id: wingo

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - name: go test
        run: cd cli && go test ./cmd/... ./internal/...

      - name: go vet
        run: cd cli && go vet ./cmd/... ./internal/...

      - name: Build
        run: cd cli && go build ./cmd/turbo/...

      - name: E2E Tests
        run: |
          npm install -g pnpm
          cd cli && make e2e

      - name: Benchmark and Smoke Tests
        run: cd cli && make bench/turbo

  examples:
    name: run examples
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Install Sponge
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y moreutils
          else
            brew install moreutils
          fi

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
        id: go

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - run: npm i -g pnpm

      - name: Check examples
        shell: bash
        run: ./scripts/run-examples.sh
