name: Go CI

on:
  push:
    branches: ["*"]

jobs:
  build:
    name: turbo CI
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.0
        id: go

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: go test
        run: cd cli && go test ./cmd/... ./internal/...

      - name: go vet
        run: cd cli && go vet ./cmd/... ./internal/...

      - name: make turbo
        run: make turbo

      - name: run bench
        run: make bench/turbo

      - name: run e2e
        run: |
          npm install -g pnpm
          make e2e
