name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: build and test
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
        id: go

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - name: Build & Unit Test
        run: yarn turbo run test --scope=cli

      - name: Lint
        run: yarn turbo run lint --scope=cli

      - name: E2E Tests
        run: |
          npm install -g pnpm
          cd cli && make e2e

      - name: Benchmark and Smoke Tests
        run: cd cli && make bench/turbo

      - name: Benchmark E2E
        run: cd cli && make bench/e2e

      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: "${{ runner.os }}-e2e-benchmark-${{ github.sha }}"
          restore-keys: |
            "${{ runner.os }}-e2e-benchmark-"

      - name: Set up comparison to main
        # if we are on a branch, we want out benchmark to be against main, if it exists
        if: ${{ github.event_name != 'push' }}
        # note that the shell command ":" does nothing and exits successfully. This lets us pass this
        # step if we don't end up doing the copy
        run: '[ -f "./cache/benchmarks-main.json" ] && cp ./cache/benchmarks-main.json ./cache/benchmarks-${{ github.head_ref }}.json || :'

      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "${{ runner.os }} Benchmark"
          # What benchmark tool the output.txt came from
          tool: "customSmallerIsBetter"
          # Where the output from the benchmark tool is stored
          output-file-path: ./cli/scripts/benchmarks.json
          # Where the previous data file is stored.
          # Note that this is somewhat of a hack to say that if we are pushing, save as the "main"
          # benchmark. If we're not, save it at this particular sha. In the previous step, we have
          # overwritten this particular sha with the main file if it exists so that we are always
          # benchmarking against main, not our previous run on this PR.
          external-data-json-path: ./cache/benchmarks-${{ github.event_name == 'push' && 'main' || github.head_ref }}.json
          save-data-file: true
          skip-fetch-gh-pages: true
          comment-on-alert: true
          comment-always: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    name: build and test
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
        id: wingo

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - name: go test
        run: cd cli && go test ./cmd/... ./internal/...

      - name: go vet
        run: cd cli && go vet ./cmd/... ./internal/...

      - name: Build
        run: cd cli && go build ./cmd/turbo/...

      - name: E2E Tests
        run: |
          npm install -g pnpm
          cd cli && make e2e

      - name: Benchmark and Smoke Tests
        run: cd cli && make bench/turbo

  examples:
    name: run examples
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Install Sponge
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y moreutils
          else
            brew install moreutils
          fi

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
        id: go

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 16

      - run: npm i -g pnpm

      - name: Check examples
        shell: bash
        run: ./scripts/run-examples.sh
