name: CLI Run Examples

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  examples:
    name: CLI run examples
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        manager: [yarn, npm]
        example: [basic, design-system, kitchen-sink]
        include:
          - os: ubuntu-latest
            manager: pnpm
            example: with-pnpm
          - os: macos-latest
            manager: pnpm
            example: with-pnpm

    runs-on: ${{ matrix.os }}
    steps:
      # TODO: what is this for? The other Go workflows don't need it
      - name: Install Sponge
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y moreutils
          else
            brew install moreutils
          fi

      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-deps
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          setup-node: false # TODO: Does this need to be customized in this workflow?

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.2.1

      # TODO: Is this necessary? The other Go jobs don't include this
      - name: Make sure pnpm always has a cache
        shell: bash
        run: |
          mkdir -p `pnpm store path`

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: ${{matrix.manager}}
          cache-dependency-path: package.json

      - name: Check \"${{matrix.example}}\" example with \"${{ matrix.manager }}\"
        shell: bash
        env:
          FORCE_COLOR: true
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_REMOTE_ONLY: true
        run: pnpm -- turbo run run-example -- "${{ matrix.example }}" "${{ matrix.manager }}"
