name: Publish npm packages

on:
  push:
    branches: [main]

jobs:
  publish-npm:
    # crates/xtask/src/publish.rs:359
    if: "startsWith(github.event.head_commit.message, 'chore: release npm packages')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: yarn

      - name: Cache cargo registry
        uses: actions/cache@v3
        # Don't care the Cargo.lock, just cache it
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: publish-npm-cargo-cache

      - run: yarn install --mode=skip-build

      - name: Build packages
        run: yarn turbo run build

      - name: Write NPM_TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_ELEVATED }}" > ~/.npmrc

      - name: Publish
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: workspace --publish
