name: release
on:
  push:
    tags:
      - v*
env:
  GO111MODULE: on
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_DOCKER_TOKEN }}
      - name: checkout code
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .makerc
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: install git-chglog
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@${{ env.GIT_CHGLOG_VERSION }}
      - run: make golang-cross-base
      - run: make golang-cross
      - run: make subimages
      - run: make docker-push
      - run: make gen-changelog
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.md
